package com.example.mongodbrealmcourse.viewmodel.utils

class ProvinceCodeMapper {
    // Khai báo một Map để ánh xạ mã tỉnh thành với tên tỉnh thành
    private val provinceCodeMap = mapOf(
        "67" to "An Giang",
        "72" to "Bà Rịa-Vũng Tàu",
        "94" to "Bạc Liêu",
        "98" to "Bắc Giang",
        "97" to "Bắc Kạn",
        "99" to "Bắc Ninh",
        "71" to "Bến Tre",
        "61" to "Bình Dương",
        "77" to "Bình Định",
        "93" to "Bình Phước",
        "86" to "Bình Thuận",
        "69" to "Cà Mau",
        "11" to "Cao Bằng",
        "65" to "Cần Thơ",
        "43" to "Đà Nẵng",
        "47" to "Đắk Lắk",
        "48" to "Đắk Nông",
        "27" to "Điện Biên",
        "39" to "Đồng Nai",
        "6" to "Đồng Tháp",
        "81" to "Gia Lai",
        "23" to "Hà Giang",
        "90" to "Hà Nam",
        "29" to "Hà Nội",
        "30" to "Hà Nội",
        "31" to "Hà Nội",
        "32" to "Hà Nội",
        "33" to "Hà Nội",
        "40" to "Hà Nội",
        "38" to "Hà Tĩnh",
        "34" to "Hải Dương",
        "15" to "Hải Phòng",
        "16" to "Hải Phòng",
        "95" to "Hậu Giang",
        "28" to "Hòa Bình",
        "80" to "Hưng Yên",
        "79" to "Khánh Hòa",
        "68" to "Kiên Giang",
        "82" to "Kon Tum",
        "25" to "Lai Châu",
        "12" to "Lạng Sơn",
        "24" to "Lào Cai",
        "49" to "Lâm Đồng",
        "62" to "Long An",
        "18" to "Nam Định",
        "37" to "Nghệ An",
        "35" to "Ninh Bình",
        "85" to "Ninh Thuận",
        "19" to "Phú Thọ",
        "78" to "Phú Yên",
        "73" to "Quảng Bình",
        "92" to "Quảng Nam",
        "76" to "Quảng Ngãi",
        "14" to "Quảng Ninh",
        "74" to "Quảng Trị",
        "83" to "Sóc Trăng",
        "26" to "Sơn La",
        "70" to "Tây Ninh",
        "17" to "Thái Bình",
        "20" to "Thái Nguyên",
        "36" to "Thanh Hóa",
        "75" to "Thừa Thiên Huế",
        "64" to "Tiền Giang",
        "41" to "TP Hồ Chí Minh",
        "50" to "TP Hồ Chí Minh",
        "51" to "TP Hồ Chí Minh",
        "52" to "TP Hồ Chí Minh",
        "53" to "TP Hồ Chí Minh",
        "54" to "TP Hồ Chí Minh",
        "55" to "TP Hồ Chí Minh",
        "56" to "TP Hồ Chí Minh",
        "57" to "TP Hồ Chí Minh",
        "58" to "TP Hồ Chí Minh",
        "59" to "TP Hồ Chí Minh",
        "84" to "Trà Vinh",
        "22" to "Tuyên Quang",
        "64" to "Vĩnh Long",
        "88" to "Vĩnh Phúc",
        "21" to "Yên Bái"
    )

    // Phương thức để nhận diện tỉnh thành từ mã tỉnh thành
    fun getProvinceNameFromCode(provinceCode: String): String {
        return provinceCodeMap[provinceCode] ?: "Không xác định" // Trả về "Không xác định" nếu không tìm thấy mã tỉnh thành
    }
}
